import jsPDF from 'jspdf'

export function generatePDF(lesson, gradeLevel, subject) {
  const pdf = new jsPDF()
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  let yPosition = 20
  const lineHeight = 7
  const margin = 20

  // Helper function to add text with wrapping
  const addWrappedText = (text, fontSize = 11, isBold = false) => {
    pdf.setFontSize(fontSize)
    pdf.setFont('helvetica', isBold ? 'bold' : 'normal')
    
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin)
    lines.forEach(line => {
      if (yPosition > pageHeight - 20) {
        pdf.addPage()
        yPosition = 20
      }
      pdf.text(line, margin, yPosition)
      yPosition += lineHeight
    })
  }

  // Header
  pdf.setFillColor(168, 85, 247)
  pdf.rect(0, 0, pageWidth, 30, 'F')
  pdf.setTextColor(255, 255, 255)
  pdf.setFontSize(22)
  pdf.setFont('helvetica', 'bold')
  pdf.text('LearnCraft AI', margin, 15)
  pdf.setFontSize(10)
  pdf.text('Where Every Lesson Comes Alive', margin, 22)
  
  yPosition = 40
  pdf.setTextColor(0, 0, 0)

  // Title
  pdf.setFontSize(18)
  pdf.setFont('helvetica', 'bold')
  pdf.text(lesson.title, margin, yPosition)
  yPosition += 10

  // Grade and Subject
  pdf.setFontSize(11)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`${subject} • ${gradeLevel} • ${lesson.duration}`, margin, yPosition)
  yPosition += 15

  // Learning Objectives
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Learning Objectives', margin, yPosition)
  yPosition += 8
  pdf.setFontSize(11)
  pdf.setFont('helvetica', 'normal')
  lesson.objectives.forEach((obj, i) => {
    addWrappedText(`${i + 1}. ${obj}`)
    yPosition += 3
  })
  yPosition += 5

  // Materials
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Materials Needed', margin, yPosition)
  yPosition += 8
  pdf.setFontSize(11)
  pdf.setFont('helvetica', 'normal')
  lesson.materials.forEach(mat => {
    addWrappedText(`• ${mat}`)
  })
  yPosition += 5

  // Introduction
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Introduction', margin, yPosition)
  yPosition += 8
  addWrappedText(lesson.introduction)
  yPosition += 5

  // Main Content
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Main Content', margin, yPosition)
  yPosition += 8
  lesson.mainContent.sections.forEach(section => {
    pdf.setFontSize(12)
    pdf.setFont('helvetica', 'bold')
    addWrappedText(section.heading, 12, true)
    yPosition += 2
    addWrappedText(section.content)
    yPosition += 3
  })
  yPosition += 5

  // Activities
  if (yPosition > pageHeight - 40) {
    pdf.addPage()
    yPosition = 20
  }
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Activities', margin, yPosition)
  yPosition += 8
  lesson.activities.forEach((activity, i) => {
    pdf.setFontSize(12)
    pdf.setFont('helvetica', 'bold')
    addWrappedText(`${i + 1}. ${activity.name} (${activity.duration})`, 12, true)
    yPosition += 2
    addWrappedText(activity.description)
    yPosition += 3
  })
  yPosition += 5

  // Assessment
  if (yPosition > pageHeight - 40) {
    pdf.addPage()
    yPosition = 20
  }
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Assessment', margin, yPosition)
  yPosition += 8
  lesson.assessment.forEach((q, i) => {
    addWrappedText(`Q${i + 1}: ${q.question}`, 11, true)
    addWrappedText(`Answer: ${q.correctAnswer}`)
    yPosition += 3
  })
  yPosition += 5

  // Closure
  if (yPosition > pageHeight - 30) {
    pdf.addPage()
    yPosition = 20
  }
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Lesson Closure', margin, yPosition)
  yPosition += 8
  addWrappedText(lesson.closure)
  yPosition += 5

  // Extensions
  if (yPosition > pageHeight - 30) {
    pdf.addPage()
    yPosition = 20
  }
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Extension Activities', margin, yPosition)
  yPosition += 8
  lesson.extensions.forEach((ext, i) => {
    addWrappedText(`${i + 1}. ${ext}`)
  })

  // Footer
  const pageCount = pdf.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i)
    pdf.setFontSize(9)
    pdf.setTextColor(128, 128, 128)
    pdf.text(`Generated by LearnCraft AI - Page ${i} of ${pageCount}`, 
      pageWidth / 2, pageHeight - 10, { align: 'center' })
  }

  return pdf
}

export function downloadPDF(lesson, gradeLevel, subject) {
  const pdf = generatePDF(lesson, gradeLevel, subject)
  pdf.save(`${lesson.title.replace(/\s+/g, '_')}_${gradeLevel}.pdf`)
}

export function formatDate(dateString) {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })
}